version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yml"]
    ports:
      - "4317:4317"
    volumes:
      - ./collector/otel-config.yml:/etc/otel-config.yml
    env_file:
      - .env
    restart: unless-stopped

  microservice-order:
    build:
      context: ./microservices/order
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8082:8082"
    restart: unless-stopped

  microservice-payment:
    build:
      context: ./microservices/payment
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8081:8081"
    restart: unless-stopped

  microservice-user:
    build:
      context: ./microservices/user
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"
    restart: unless-stopped
